### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by idealhack** [daaku/syno#1]
This error occurs when I call `syno.NewClient()`.

The reason is Synology returns a HTML (sth. like a splash screen) instead of JSON first, [this line](https://github.com/daaku/syno/blob/53ff0eb85a606352bacaf35b37510e58afe99828/syno.go#L140) would fail and return the error.

When I request the same URL in a browser, it will returns a JSON eventually, even though it's 400, maybe there are some mistakes in my parameters.

I'm new to Synology API, can you reproduce this error? Example code are like:

```
c, err := syno.NewClient(
	syno.ClientRawURL("https://example.quickconnect.to"),
	syno.ClientLogin(syno.AuthLogin{
		Account: "account",
		Password: "password",
		Session:  "DownloadStation",
		Format:   "cookie",
	}),
)
if err != nil {
	log.Fatalf("error while login to synology: %s", err)
}
log.Println(c)
```

**Comment by daaku** [comment]
That may be because the URL you gave the client is for the web UI rather than the API. I no longer have a Synology NAS so can't help diagnose or fix the error unfortunately! Happy to accept a pull request if you figure out a solution :)

**Comment by idealhack** [comment]
Hi, glad to see your reply!

This issue also been reported in thavel/synolopy#10, it only happen to quickconnect hostnames. It seems that better error message is the best we can do for this situation.

**Comment by idealhack** [comment]
I'm closing this because clients can't do many things about it.
